apiVersion: v1
kind: ConfigMap
metadata:
  name: tunnel-config
  namespace: ssh-tunnel
data:
  BASTION_USER: "user"
  BASTION_HOST: "bastion.example.com"
  REMOTE_PORT: "36443"                 # unique per cluster
  CLUSTER_NAME: "mycluster"
  BASTION_KUBECONFIG_DIR: "/home/user/.kube"
  BASTION_KUBECONFIG_NAME: "mycluster.yaml"
